### ISSUE TITLE
Requesting Sync feature for Joplin Server

### ISSUE THREAD

**Issue by kestr31** [joplin-vieweb/joplin-vieweb#2]
Using Joplin on mobile devices such as tablets was always inconvenient due to lack of features of mobile apps.

However, using this webapp helped to solve that problem. I'm impressed about your work and I'd like to say thank you.

But currently, this app can only sync to NextCloud WebDAV service for now.

May I request a feature so sync with Joplin Server? This will make an advantage due to faster sync.

Thank you again.

**Comment by gri38** [comment]
You welcome and thanks for your feedback.
I'll have a look to joplin server.

**Comment by kestr31** [comment]
Hello :)

Target I meant is 9, the [Joplin Server](https://hub.docker.com/r/joplin/server).

I think that person who try to deploy web version of joplin will prefer Joplin Server since he/she is very likely to own his/her resource to deploy these services. Supporting both will be nice for potential users but due to this reason, I think sync target 9 should be prioritized.

**Comment by gri38** [comment]
Done in v2.1.0.
@kestr31 can you test please: I didn't install a joplin server.

**Comment by kestr31** [comment]
Thank you again for your fast reply and I will reply as I finish testing it on my server. Thank you.

**Comment by gri38** [comment]
you welcome. Thanks for the test.
