### ISSUE TITLE
go anywhere for search feature

### ISSUE THREAD

**Issue by gri38** [joplin-vieweb/joplin-vieweb#20]
Like vscode or sublime text ctrl+p

Text = search in title
@ = search in body
# = search tags

With and or op?

**Comment by kja999** [comment]
Just my opinion, but this for me is the key next feature.
Not sorting is ok, but I cannot do much with my notes until I can find them. I have too much data to scroll through them trying to remember a title I added

**Comment by gri38** [comment]
Hi @kja999 
I'm "happy" you requested this feature, it may say you use joplin vieweb.

I agree this feature is missing.

I'll try to take some time those days to implement.

If you can try, when I'll ask, the serach feature, that would be great.
Especially I think I'll implement without pagination (ie: I return every results, **not** 10 first for instance, then a [MORE...] button.... ).

Without pagination will be ok for me (I don't have so much notes), but it may not fit everyone needs.

But I like doing a feature first, then optimize only if requested (if used).

**Comment by kja999** [comment]
Thanks for the effort you put in!
I'll definitely test if you have an update.

A basic search with all results is fine for my use. I have many notes and notebooks and even now in the desktop client I don't use any of the advanced search, just text phrases.

**Comment by gri38** [comment]
Hi.

I don't have a lot of time for this projests those time.
I've implemented a simple search feature, respecting the search syntax of joplin.
  - Press f key, or click magnifying glass icon
  - Search syntax: documented [here](https://discourse.joplinapp.org/t/search-syntax-documentation/9110) or [here](https://joplinapp.org/help/#searching).

I didn't test a lot. Don't hesitate to give feed-back, or ask for specific search feature.

**Comment by kja999** [comment]
Amazing, thanks for this! 
Updated via docker, had to clear the cache on the browser but everything is working perfectly!
