### ISSUE TITLE
MathJax/ KateX rendering

### ISSUE THREAD

**Issue by DouisLavid** [joplin-vieweb/joplin-vieweb#25]
Hello,
I have no clue whether it is something trivial or extremely complex to implement, but I would love to see latex rendering in joplin-webview.
I mainly use it for math stuff, and it works great on Joplin desktop :
![image](https://user-images.githubusercontent.com/52973262/170561704-ee72d498-4fa1-48e4-9a94-15b88f6cba7e.png)
However, Latex is not rendered in joplin-vewview:
![image](https://user-images.githubusercontent.com/52973262/170561884-96608167-42fb-4b69-b5c8-a56c79edd343.png)
I mainly use webvue to show my notes on computers on which Joplin is not installed (or on which I am not willing to put my synchronization credentials), and it is a bit of a bummer to miss this essential (to me) feature.

Anyway, this project really fills a gap for me and love it <3, keep it up and let me know if I can be of any help.

**Comment by gri38** [comment]
Hello.

Thanks for feedback.

I'll have a look (after the ascension week end).
It should be quite straightforward.

Could you please give me some text you would like to test, block, inline... otherwise I'll use some samples from the web

**Comment by gri38** [comment]
Hello @DouisLavid 

I give a first try this morning:
![image](https://user-images.githubusercontent.com/26554495/170932740-66e22d36-b4d3-4ce9-8007-5a90af2dd41b.png)

I still have some things to fix:

- TOC disappeared 
- the latex are rendered in code blocks or inline code (they shouldn't)
- in the sum sign (sigma), the range are not on top and bottom of sigma sign, they are exposant and indice just after the sigma sign... I'll have to search the html render options I think.

Could you send me some your sample (you wrote as comment of this issue) so I can try with \begin \ end, aligned ...

**Comment by gri38** [comment]
Second try this evening with KaTex: easier and we are almost there (still some adjustments to not make latex in some cases, if I can):
![image](https://user-images.githubusercontent.com/26554495/171055089-1b7d5a6d-7ed3-43b1-af2a-a4d2b5575172.png)

**Comment by gri38** [comment]
Fix in 2.2.0.
Cf. [this release](https://github.com/joplin-vieweb/joplin-vieweb/releases/tag/v2.2.0) for details.

I close the ticket, please test and comment (even if it works, it's a pleasure)
