### ISSUE TITLE
Unable to synchronize

### ISSUE THREAD

**Issue by mike8206** [joplin-vieweb/joplin-vieweb#40]
Sorry for bothering,
I have 2 problems with the web editor.

1. I got this **error message** with correct settings. (Could synchronize correctly with Desktop app)
```
Synchronisation target: Joplin Server (Beta) (9)
Starting synchronisation...
Fetched items: 1/66.
/app/joplin/lib/node_modules/joplin/node_modules/@joplin/lib/database-driver-node.js:23
const output = new Error(msg.join(': '));
^

Error: Error: SQLITE_ERROR: table item_changes has no column named source: INSERT INTO item_changes (item_type, item_id, type, source, created_time, before_change_item) VALUES (?, ?, ?, ?, ?, ?): 1,4a97965587ee416ba96386fc55e22577,1,2,1661869804235,
at DatabaseDriverNode.sqliteErrorToJsError (/app/joplin/lib/node_modules/joplin/node_modules/@joplin/lib/database-driver-node.js:23:18)
at JoplinDatabase.sqliteErrorToJsError (/app/joplin/lib/node_modules/joplin/node_modules/@joplin/lib/database.js:34:30)
at JoplinDatabase. (/app/joplin/lib/node_modules/joplin/node_modules/@joplin/lib/database.js:133:36)
at Generator.throw ()
at rejected (/app/joplin/lib/node_modules/joplin/node_modules/@joplin/lib/database.js:6:65)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
code: 'SQLITE_ERROR'
}

Node.js v18.4.0
```

2. The **timestamp** of *Last synchronisation* was wrong. (might due to **timezone**)

Thank you for making and sharing this good web editor for Joplin. I appreciate it a lot. 
Hope this problem could be solved. Thanks! :)

**Comment by gri38** [comment]
Hello.

About the synchro issue: can you give me the desktop app you used (which version). Maybe joplin server expects a different version than the joplin CLI I use.

The CLI joplin currently used in my docker image is 
Joplin CLI Client Copyright © 2016-2022 Laurent Cozic joplin 2.8.1 (prod, linux) Sync Version: 3 Profile Version: 41 Keychain Supported: No

About time of last synchro: indeed utf vs local date time. In another project, I struggled for a long time to understand how to deal with locale time in django, but now I know: I'll fix it in a future release. For the moment I live with the 2 hours shift.

**Comment by gri38** [comment]
I've just check: last official version (2.8.8) has the same versions of sync (3) than joplin terminal in my docker image... so it's probably not a  version issue. Please check anyway your version in the desktop application (menu Help > About Joplin)

**Comment by gri38** [comment]
I've just produced a new docker with the last joplin CLI, and in fact I was already in the last joplin CLI... so ... Maybe you are late in the desktop app ?

**Comment by mike8206** [comment]
> I've just produced a new docker with the last joplin CLI, and in fact I was already in the last joplin CLI... so ... Maybe you are late in the desktop app ?

The version of desktop app:
Joplin 2.8.8 (prod, win32)
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

I think the problem was solved after the server repeating synchronized for several times!

And the message showed below:
Synchronisation target: Joplin Server (Beta) (9)
Starting synchronisation...
Completed: 30/08/2022 23:15 (972ms)
Downloading resources...

Thank you very much!

**Comment by gri38** [comment]
Hello @mike8206 
Can you have a look to https://github.com/joplin-vieweb/joplin-vieweb/issues/43 please.
