### ISSUE TITLE
Certbot crashes with error "exec /bin/start_cert.sh: exec format error"

### ISSUE THREAD

**Issue by symphonyoffeelings** [joplin-vieweb/joplin-vieweb#46]
joplin-vieweb-joplin-vieweb-certbot-1  | exec /bin/start_cert.sh: exec format error

Running in DigitalOcean, using Docker CE.

**Comment by gri38** [comment]
Hello.
I think it's because my certbot image is only built for those arch: linux/amd64,linux/arm64
Could you say which arch are you using on DigitalOcean ?

**Comment by symphonyoffeelings** [comment]
Interesting... "dpkg --print-architecture" returns "amd64".

**Comment by gri38** [comment]
OK... so it's... something else ;-)
However, even if it doesn't solve directly your question, but on this page: https://www.digitalocean.com/pricing/app-platform I read: "checkmarkAutomatic HTTPS".
So you may not need certbot ? neither joplin-vieweb-nginx ?

**Comment by gri38** [comment]
No news... I close this issue. Feel free to open it again if needed.
