### ISSUE TITLE
Sync ongoing for 24 hours

### ISSUE THREAD

**Issue by kja999** [joplin-vieweb/joplin-vieweb#49]
Hi,
I have setup on a QNAP nas using the joplin only compose.
All seems ok but the sync doesn't seem to be working.

There was an initial update which then stopped to prompt for the master encryption key (added with the docker exec command on the server), but since I am not sure anything is working.

The service repeats these messages every few seconds:
{"info": "2023-05-24T07:15:06.925Z", "output": "Synchronisation target:  (6)\nStarting synchronisation...\nCompleted: 24/05/2023 07:15 (5s)\nDownloading resources...\n", "error": ""}

Is this an error or a complete step ?

**Comment by gri38** [comment]
Hi.

I tried to handle e2ee in a branch, but I finally gave up... (you are speaking about e2ee, aren't you?).

My dev was almost working, but I encountered issues when I tried to disable, then enable again... I don't know if Joplin is more robust now than when I did...

I unfortunately cannot spend time at this moment... Maybe [this discussion](https://github.com/joplin-vieweb/joplin-vieweb/issues/6) may help you ?
