### ISSUE TITLE
Bad Request (400)

### ISSUE THREAD

**Issue by simpleacc** [joplin-vieweb/joplin-vieweb#50]
Hello,

I would like to use joplin-vieweb but I have a problem with the configuration. When I start it... a 400 error appears.
Because I have already the nginx and certbot, I am using the docker-compose-joplin-only.yml with the following config:

```
version: '3.4'

x-common-variables: &common-variables
    ORIGINS: "'https://joplin.mydomain.com'"

services:
    django-joplin-vieweb:
        container_name: JOPLIN-VIEWER
        image: gri38/django-joplin-vieweb:latest
        environment:
            <<: *common-variables
        restart: unless-stopped
        #ports:
            #- 8000:8000
        volumes:
            - joplin:/root/.config/joplin:ro
            - joplin-vieweb:/root/.config/joplin-vieweb
        networks:
            DockerVLAN:
                ipv4_address: 10.0.0.10

    joplin-terminal-xapi:
        container_name: JOPLIN-XAPI
        image: gri38/joplin-terminal-xapi:latest
        restart: unless-stopped
        volumes:
            - joplin:/root/.config/joplin
        networks:
            DockerVLAN:
                ipv4_address: 10.0.0.11
volumes:
    joplin:
    joplin-vieweb:

networks:
    DockerVLAN:
        external: true
```

Is there someting missing? I am using my own external network.

Thanks!

**Comment by gri38** [comment]
Hi.

It not easy to answer because I don't know about your nginx.
First of all: didn't you forget the /joplin at the end of the url ? See [here](https://github.com/joplin-vieweb/joplin-vieweb#configuration-and-usage).

Let's answer some questions, pleaase, in order to clarify:

- Q1: error 400: who does block the request? nginx or django-joplin-vieweb?
  - Q1': do you know how to answer this question?
- Q2: is your nginx running on your OS, or on a docker container ?
  -  Q2': if it runs on docker: on the same network ?

**Comment by simpleacc** [comment]
> Hi.
> 
> It's not easy to answer because I don't know about your nginx.
> 
> First of all: didn't you forget the /joplin at the end of the url ? See [here](https://github.com/joplin-vieweb/joplin-vieweb#configuration-and-usage).
> 
> Your docker-compose seems good, but why did you remove
> 
> ```yaml
> depends_on:
>       - joplin-terminal-xapi
> ```
> 
> from services: django-joplin-vieweb: ?
> 
> Let's answer some questions, pleaase, in order to clarify:
> 
> * Q1: error 400: who does block the request? nginx or django-joplin-vieweb?
>   
>   * Q1': do you know how to answer this question?
> * Q2: is your nginx running on your OS, or on a docker container ?
>   
>   * Q2': if it runs on docker: on the same network ?
> 
> Then, we can do some ping tests from one container to another, after you answered.

Hello,

Thanks for your answer.
Yes, I am using http://10.0.17.127:8000/joplin and with this I get the 400 bad gateway.
I am going to add the 'depends_on' in the compose right now.
About the questions:
Q1: To be honest I do not know how to check it. I am checking the docker logs (for django-joplin-vieweb) and I cann ot see anything.
Q2: My nginx is running in a Debian virtual machine, in another VLAN. But the firewall access is enabled in both ways.

Maybe... Must I add some variables in the compose like user and password?

Best regards,

**Comment by gri38** [comment]
Hi again.

I think you need the port mapping. In your docker-compose: uncomment the port mapping 8000:8000 in django-joplin-vieweb service.

Then, before debugging your nginx config, you may want to check if it cann communicate with the django-joplin-vieweb container.

Here how you van do:
- On the server running docker and joplin-veiweb:
  - `sudo docker container ls`
     will give you the list of containers. One is "**e27**0d3924beb   gri38/django-joplin-vieweb:latest   "/bin/sh /app/ru...."
  - follow the logs of this container with `sudo docker logs e27 --follow` (change e27 by the beginning of your cpontainer id from previous command).
  - Let this terminal running, you can see the logs.
- On the server running your nginx:
    - `ping 10.0.0.10`
    - you should have a response: if not, this is your first issue: your nginx cannot access your "joplin server"
  - If it's ok, lets check a request to joplin-vieweb: from your nginx server terminal: `curl http://10.0.0.10:8000/joplin/note_error/`
    - If it's ok, you should have an answer like that:
```html
<!doctype html>
<html lang="en">
<head>
  <title>Bad Request (400)</title>
</head>
<body>
  <h1>Bad Request (400)</h1><p></p>
</body>
</html>
``` 

This Bad Request (400) is normal, and you can see why in the docker logs you are following, in which you should see this kind of output:

```
HTTP b'GET' request for ['127.0.0.1', 35466]
Invalid HTTP_HOST header: '10.0.0.10'. You may need to add '10.0.0.10' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/asgiref/sync.py", line 486, in thread_handler
    raise exc_info[1]
  File "/root/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
  File "/root/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 148, in __acall__
    response = await sync_to_async(
  File "/root/.local/lib/python3.9/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.local/lib/python3.9/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/root/.local/lib/python3.9/site-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '10.0.0.10'. You may need to add '10.0.0.10' to ALLOWED_HOSTS.
Bad Request: /joplin/note_error/
HTTP 400 response started for ['127.0.0.1', 35466]
HTTP close for ['127.0.0.1', 35466]
HTTP response complete for ['127.0.0.1', 35466]
127.0.0.1:35466 - - [13/Jun/2023:08:40:42] "GET /joplin/note_error/" 400 143
```


If you arrived until here and have this error 400 in the logs of django-joplin-vieweb, it means your configuration seems ok, and we have to go further.
Otherwise, we have to find what doesn't work, and probably go to nginx configuration.

FYI, my nginx config looks like that (I changed the address so it looks like your configuration):
```
server {
    server_name joplin.mydomain.com;
    client_max_body_size 50M;

    location / { # default is joplin
        try_files $uri @proxy_to_app_joplin;
    }

    location @proxy_to_app_joplin {
        proxy_pass http://10.0.0.10:8000;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
    }
    
    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/joplin.mydomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/joplin.mydomain.com/privkey.pem;
}

```

**Comment by simpleacc** [comment]
Hello,

Thanks for you help.
Yes, all looks like your results. Including the curl http://10.0.0.10:8000/joplin/note_error/

Just to know... Must I access via domain name or IP? Currently I am trying to access with the http://10.0.0.10:8000/joplin. Must I use the name instead of? 

Best regards,

**Comment by gri38** [comment]
Hello.

You're welcome.

About IP versus name: if I understoof well, your nginx is on a separate machine, so I think it doesn't make any difference.

So, now we know your OS with nginx is able to communicate with joplin stuff, let's check why it doesn't work.
I suspect "host not allowed", and maybe a configuration in nginx...

Can you do that:

- On joplin-vieweb server: like on the previous tests, you follow the logs, and keep the console opened to read them.
  - You can inpute a few `Enter` to have a space and see new logs.
- On the server running your nginx, if you logs, you may have a look to the logs (I think it should be `tail -f /var/log/nginx/access.log` and `tail -f /var/log/nginx/error.log`
- On your webbrowser: go to `https://yourdomain.com/joplin/note_error`

Do you see new logs in joplin-vieweb container ?
Can you paste them ?
If not, do you see any logs in your nginx?

**Comment by gri38** [comment]
Hi.

So it seems it's "just" an host allowed issue.

Did you write that on your docker-compose file:

```yaml
x-common-variables: &common-variables
   ORIGINS: "'https://joplinviewer.domain.com'"
```

?

**Comment by simpleacc** [comment]
Hello,

Nope, in the joplin-viewer docker compose I have added the joplin website, not the viewer. 

Regards,

**Comment by simpleacc** [comment]
Oh, man...
The thing was that I was editing the config file but because it already exists in the volume it did not change anything 😅
So, in the docker compose I have added my joplin viewer domain, joplin domain and proxy LAN ip and then I have deleted the volume with the docker volume prune and started the docker compose.
Now it works! At least I can see the login screen hehe. Which user must I use?

Regards and thank you so much for all you help!

**Comment by gri38** [comment]
Arf, that's not the first time user has this issue !!
I really should fix that bug: #34 
Sorry I forget about that !!!

I'll fix it for the next release !

About the error for user, I don't really know why it complains about "no such table". It may be because of the volume prune.

I think the simplest thing is to start again "from scratch", at least for django-joplin-vieweb:

- First note the id of your django-joplin-vieweb container with `sudo docker container ls`   => **XXX**
- Then note the id of the volume: `sudo docker volume ls`: it is the volume ending with joplin-vieweb: **YYY_joplin-vieweb**

```bash
sudo docker-compose down
sudo docker container rm XXX
sudo docker volume rm YYY_joplin-vieweb
sudo docker-compose up -d
```


I'm sorry it's been so coplicated for you.
I really should fix the bug about taking docker-compose changes into account !!!


Let me know if you succeed!

**Comment by simpleacc** [comment]
Hello,

Thanks for the answer.
I have followed your (except the `sudo docker container rm XXX` because with the docker-compose down it auto remove this) and is not working, the Server Error (500) still there. I am trying this with the user admin and password admin here: https://joplin-web.domain.com/admin is it correct?

Regards,

**Comment by TuRDMaN** [comment]
I'm encountering the same problem. I already have Nginx Proxy Manager running, so I used that as my reverse proxy. Everything is running in Docker with Portainer.

From the logs:
`CommandError: /app/manage.py already exists. Overlaying a project into an existing directory won't replace conflicting files.
rm: can't remove './server/settings.py': No such file or directory
Let's create django settings files (origins: "'http://localhost', 'http://joplin.domain.xyz', 'http://1.123.145.167'") in version # version: 2.0
ln: ./settings/settings.py: File exists
ALLOWED_HOSTS =  ['']
CSRF_TRUSTED_ORIGINS =  ["'http://localhost', 'http://joplin.domain.xyz', 'http://1.123.145.167'"]

0 static files copied to '/app/staticfiles', 225 unmodified.
ALLOWED_HOSTS =  ['']
CSRF_TRUSTED_ORIGINS =  ["'http://localhost', 'http://joplin.domain.xyz', 'http://1.123.145.167'"]
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
ALLOWED_HOSTS =  ['']
CSRF_TRUSTED_ORIGINS =  ["'http://localhost', 'http://joplin.domain.xyz', 'http://1.123.145.167'"]
Admin accounts can only be initialized if no Accounts exist
ALLOWED_HOSTS =  ['']
CSRF_TRUSTED_ORIGINS =  ["'http://localhost', 'http://joplin.domain.xyz', 'http://1.123.145.167'"]
Starting server at tcp:port=8001:interface=127.0.0.1
HTTP/2 support not enabled (install the http2 and tls Twisted extras)
Configuring endpoint tcp:port=8001:interface=127.0.0.1
Listening on TCP address 127.0.0.1:8001`

After opening https://joplin.domain.xyz/admin in my browser:
`HTTP b'GET' request for ['127.0.0.1', 44374]
Invalid HTTP_HOST header: 'joplin.domain.xyz'. You may need to add 'joplin.domain.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/root/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/root/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 146, in __acall__
    response = await sync_to_async(
  File "/root/.local/lib/python3.9/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.local/lib/python3.9/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/root/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'joplin.domain.xyz'. You may need to add 'joplin.domain.xyz' to ALLOWED_HOSTS.
Bad Request: /admin
HTTP 400 response started for ['127.0.0.1', 44374]
HTTP close for ['127.0.0.1', 44374]
HTTP response complete for ['127.0.0.1', 44374]
127.0.0.1:44374 - - [24/Jan/2024:17:27:07] "GET /admin" 400 143`

So it looks like CSRF_TRUSTED_ORIGINS is being properly opulated from the environment variables, but ALLOWED_HOSTS is remaining blank. Is it possible to set that from the docker environment variables, or some other way?

**Comment by gri38** [comment]
Hello @TuRDMaN 
Could you please write your docker-compose.yml file (rename your domain and IPs).
Just to check the syntax.

**Comment by TuRDMaN** [comment]
Docker-compose
```
version: '3.6'
services:
 #
 ##########
 # Joplin #
 ##########
  joplin-vieweb:
    image: gri38/django-joplin-vieweb:latest
    container_name: joplin-vieweb
    depends_on:
      - joplin-terminal-xapi
    environment:
      - ORIGINS="'${ORIGIN1}', '${ORIGIN2}', '${ORIGIN3}'"
    restart: unless-stopped
    volumes:
      - /home/user/.joplin:/root/.config/joplin:ro
      - /home/user/.joplin-vieweb:/root/.config/joplin-vieweb
    networks:
      - npm_default

  joplin-terminal-xapi:
    image: gri38/joplin-terminal-xapi:latest
    container_name: joplin-terminal-xapi
    restart: unless-stopped
    volumes:
      - /home/user/.joplin:/root/.config/joplin
    networks:
      - npm_default 
# 
###########
networks: #
###########
  npm_default:
    name: npm_default
    external: true
```

Portainer Evironment Variables
```
ORIGIN1=http://localhost
ORIGIN2=http://joplin.domain.xyz (domain)
ORIGIN3=http://1.123.145.167 (public IP)
```

**Comment by gri38** [comment]
Hi @TuRDMaN 
It's strange because your docker-compose.yml file seems ok, but the logs shows the origins are not parsed correctly.

In your logs we can see:
ALLOWED_HOSTS =  ['']
CSRF_TRUSTED_ORIGINS =  ["'http://localhost', 'http://joplin.domain.xyz', 'http://1.123.145.167'"]

In my logs for instance:
ALLOWED_HOSTS =  ['mine.fr', '12.34.56.78']
CSRF_TRUSTED_ORIGINS =  ['https://mine.f', 'https://12.34.56.78']

Here is how I would debug:
* Try to input directly your origins in the docker-compose file
```yaml
environment:
      - ORIGINS="'http://localhost', 'http://joplin.domain.xyz', 'http://1.123.145.167'"
```
* sudo docker-compose up
* Read the output: what are ALLOWED_HOSTS and CSRF_TRUSTED_ORIGINS  ?
* If it doesnt' change, just try with 
```yaml
environment:
      - ORIGINS="'http://toto.com'"
```
Just to see if it's taken into account: do your docker-compose up and watch allowed hosts and origins values.

Let me know

**Comment by TuRDMaN** [comment]
I've changed the Origins section to
```
    environment:
      - ORIGINS="'https://joplin.redpill.online'"
```

But
```
Let's create django settings files (origins: "'https://joplin.domain.xyz'") in version # version: 2.0
ALLOWED_HOSTS =  ['']
CSRF_TRUSTED_ORIGINS =  ["'https://joplin.domain.xyz'"]

225 static files copied to '/app/staticfiles'.
ALLOWED_HOSTS =  ['']
CSRF_TRUSTED_ORIGINS =  ["'https://joplin.domain.xyz'"]
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
ALLOWED_HOSTS =  ['']
CSRF_TRUSTED_ORIGINS =  ["'https://joplin.domain.xyz'"]
Admin accounts can only be initialized if no Accounts exist
ALLOWED_HOSTS =  ['']
CSRF_TRUSTED_ORIGINS =  ["'https://joplin.domain.xyz'"]
Starting server at tcp:port=8001:interface=127.0.0.1
HTTP/2 support not enabled (install the http2 and tls Twisted extras)
Configuring endpoint tcp:port=8001:interface=127.0.0.1
Listening on TCP address 127.0.0.1:8001
HTTP b'GET' request for ['127.0.0.1', 50870]
Invalid HTTP_HOST header: 'joplin.domain.xyz'. You may need to add 'joplin.domain.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/root/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/root/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 146, in __acall__
    response = await sync_to_async(
  File "/root/.local/lib/python3.9/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.local/lib/python3.9/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/root/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'joplin.domain.xyz'. You may need to add 'joplin.domain.xyz' to ALLOWED_HOSTS.
Bad Request: /admin
HTTP 400 response started for ['127.0.0.1', 50870]
HTTP close for ['127.0.0.1', 50870]
HTTP response complete for ['127.0.0.1', 50870]
127.0.0.1:50870 - - [26/Jan/2024:15:55:32] "GET /admin" 400 143
```

**Comment by TuRDMaN** [comment]
I've changed the Origins section to
```
    environment:
      - ORIGINS="'https://joplin.domain.xyz"
```

But
```
Let's create django settings files (origins: "'https://joplin.domain.xyz'") in version # version: 2.0
ALLOWED_HOSTS =  ['']
CSRF_TRUSTED_ORIGINS =  ["'https://joplin.domain.xyz'"]

225 static files copied to '/app/staticfiles'.
ALLOWED_HOSTS =  ['']
CSRF_TRUSTED_ORIGINS =  ["'https://joplin.domain.xyz'"]
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
ALLOWED_HOSTS =  ['']
CSRF_TRUSTED_ORIGINS =  ["'https://joplin.domain.xyz'"]
Admin accounts can only be initialized if no Accounts exist
ALLOWED_HOSTS =  ['']
CSRF_TRUSTED_ORIGINS =  ["'https://joplin.domain.xyz'"]
Starting server at tcp:port=8001:interface=127.0.0.1
HTTP/2 support not enabled (install the http2 and tls Twisted extras)
Configuring endpoint tcp:port=8001:interface=127.0.0.1
Listening on TCP address 127.0.0.1:8001
HTTP b'GET' request for ['127.0.0.1', 50870]
Invalid HTTP_HOST header: 'joplin.domain.xyz'. You may need to add 'joplin.domain.xyz' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/root/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/root/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 146, in __acall__
    response = await sync_to_async(
  File "/root/.local/lib/python3.9/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.local/lib/python3.9/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/root/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'joplin.domain.xyz'. You may need to add 'joplin.domain.xyz' to ALLOWED_HOSTS.
Bad Request: /admin
HTTP 400 response started for ['127.0.0.1', 50870]
HTTP close for ['127.0.0.1', 50870]
HTTP response complete for ['127.0.0.1', 50870]
127.0.0.1:50870 - - [26/Jan/2024:15:55:32] "GET /admin" 400 143
```

**Comment by gri38** [comment]
Hi @TuRDMaN 
Last update.
It was a matter of docker-compose syntax.

# That works:
```yml
services:
  django-joplin-vieweb:
    [...]
    environment:
      - ORIGINS='https://localhost', 'http://other'
```
It will print:
```txt
ALLOWED_HOSTS =  ['localhost', 'other']
CSRF_TRUSTED_ORIGINS =  ['https://localhost', 'http://other']
```
# thanks:
It's a tricky issue.  
I've documented it here.  
Thanks for bearing with the initial challenges and reporting the problem.

**Comment by gri38** [comment]
@TuRDMaN I close the issue, please feel free to answer, and open again if issue is still here.
