### ISSUE TITLE
settings doesn't load Error while getting configuration.

### ISSUE THREAD

**Issue by syllver23** [joplin-vieweb/joplin-vieweb#52]
notes are working properly, but setting page doesn't load. 
I'm using Nginx with a subdomain setup.

I get this error on the website
Error while getting configuration.

and this in terminal
`joplin                         | Application instance <Task pending name='Task-6' coro=<ASGIHandler.__call__() running at /root/.local/lib/python3.9/site-packages/django/core/handlers/asgi.py:155> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.9/asyncio/futures.py:384, <TaskWakeupMethWrapper object at 0x7f0e8b489460>()]>> for connection <WebRequest at 0x7f0e8bc12910 method=GET uri=/joplin/config/ clientproto=HTTP/1.1> took too long to shut down and was killed.
`

thank you so much for this docker image. it is outstanding!

**Comment by gri38** [comment]
Hello.

I think I had this issue on my raspberry... I think it was working well on me dev computer (which is powerful) but not very good on my raspberry (I'm speaking about the config page only).

I don't remember how I did on my raspberry to get the config page ... maybe I tried several time.

What is your server config ?

**Comment by syllver23** [comment]
I'm running ubuntu server 18.04  with 2GB RAM.
It ended up being the internal docker network was being blocked by firewall. allowing the docker network like 192.168.x.1 made the notes work, but I tried allowing 192.168.x.2 and 192.168.x.3 and now it works.
