### ISSUE TITLE
Cannot search for words containing letter F

### ISSUE THREAD

**Issue by kja999** [joplin-vieweb/joplin-vieweb#54]
Hi Nicolas,

Minor issue with the new search function... 
you cannot search for any word with letter f as it reloads the search page whilst typing...  :-)

**Comment by gri38** [comment]
He he: well seen ;-)

I paid attention to disable the f shortcut in notebook creation, in tag edition, and so on... but not on the new search feature ;-)
I'll do a new release ASAP.

Thanks for your testing.

**Comment by gri38** [comment]
Fixed in [2.4.1](https://github.com/joplin-vieweb/joplin-vieweb/releases/tag/v2.4.1)
