### ISSUE TITLE
Attachment failed warning stops image attachments if delayed POST

### ISSUE THREAD

**Issue by kja999** [joplin-vieweb/joplin-vieweb#55]
Hi,

Sorry to add another :-)

I had a running issue where I couldn't attach images, unless they were very small.
After digging around I have found it's not the image size settings etc, but actually the code that warns of a failed attachment assuming an error but was just a delay on writing data to server.

To test, I pasted an image, copied to markdown, saved, removed the error message and added the markdown back in to the image resource and it was there.
I removed the code with a dirty hack and I can attach images again.

File.. edit_session.py
Line 129.. I removed the md substitution code, to just keep the existing md for the image with "md = md"

Not a solution, but a workaround for me.

file now reads as below:
        # let's update md for images:
        for one_id, one_title, one_attachment in attachment_data:
            pattern = f"\\[[^]]*]\\(/joplin/edit_session_ressource/{re.escape(session_id)}/{re.escape(one_attachment)}\\)"
            if one_id is None:
                md = md
            else:
                repl = f"[{one_title}](:/{one_id})"
                md = re.sub(pattern, repl, md)

        return md

**Comment by kja999** [comment]
Sorry, i'm wrong, the images are not being synced.

**Comment by gri38** [comment]
Hello.

You are very welcome to input bugs, or "things hard to do": it helps improving, either the product or its doc.

Maybe your issue root cause is your reverse proxy ? 
Have a look to the nginx conf I provide [here](https://github.com/joplin-vieweb/joplin-vieweb-nginx/blob/main/nginx_conf/joplin_vieweb.conf.template#L3): it allows upload of images up to 50MB.

Couldn't it be your issue ?

I will add a paragraph in the doc about that.

Let me know if it was that.

**Comment by kja999** [comment]
I dont think this is my issue.
My setup is running on internal network (accessed via VPN only) so no cloud/certificates included. I am just running the web client and terminal dockers.

I skimmed the nginx.conf and apart from the 443 stuff, nothing appears significantly different.

When tracing the network actions, all seems to have posted correctly (at least no errors).
![image](https://github.com/joplin-vieweb/joplin-vieweb/assets/134485095/5f6d7473-20b0-4727-ac06-d0ebb9371201)

Last part of the puzzle, image attachments under 10kb seem to work fine (roughly 2cm x 2cm of the screen), which led me think this must be performance related not setup.

**Comment by kja999** [comment]
Progress!
In the nginx error log on the terminal server has many of these entries:
023/07/24 11:39:14 [crit] 11#11: *10678 open() "/var/lib/nginx/tmp/client_body/0000000018" failed (13: Permission denied), client: 172.29.4.3, server: , request: "POST /resources?token=ea3c10880b2a8893136dce8b1d8f3bf7890fd019aaaab3a29e04e545a7bfe537a6d8d39161aa9b579976e3a173216f828ff0de08125128e20438095ffd4846e8 HTTP/1.1", host: "joplin-terminal-xapi:8080"

I have tried modifying folder permissions but same message each time (so far0.

**Comment by gri38** [comment]
so it seems it's a issue of the reverse proxy, not joplin vieweb itself.
I close, but we can open again if I'm wrong.
