### ISSUE TITLE
Support for Encrypted Notes

### ISSUE THREAD

**Issue by HB9HIL** [joplin-vieweb/joplin-vieweb#59]
Hello there

I'm using an encryption on Joplin Desktop and Mobile. 

I couldn't figure out how to enable encryption in Vieweb. Is it possible? 

My Vieweb Shows me something but seems like it does no decrypt those notes

![image](https://github.com/joplin-vieweb/joplin-vieweb/assets/80885850/dc60caaa-b894-4ad7-9acc-a4b9acc0a2c2)

**Comment by gri38** [comment]
Hello.

Short answer: no.

But ...  you can give some try with a version compiled with the support.
Have a look to this post:
https://github.com/joplin-vieweb/joplin-vieweb/issues/6#issuecomment-1633971893 

Please save your notes before ;-)


If ever you try and have success or difficulties, please share.

**Comment by gri38** [comment]
Duplicated of #6
