### ISSUE TITLE
"S3 oss" new synchronization method is required

### ISSUE THREAD

**Issue by ouyangjunyi** [joplin-vieweb/joplin-vieweb#61]
<img width="696" alt="image" src="https://github.com/joplin-vieweb/joplin-vieweb/assets/31798535/4077334e-d022-4baa-87a2-349f0815571d">

**Comment by gri38** [comment]
Done.
I've released https://github.com/joplin-vieweb/joplin-vieweb/releases/tag/V2.5.0 
Could you please try: I tested only the good configuration of joplin terminal, but not the true sync with a S3 bucket.
@ouyangjunyi

**Comment by gri38** [comment]
BTW, @ouyangjunyi ,without taking offense or personally, but when you encounter a bug, could you use a bit of politeness: hello, please...
To phrase it differently:

What I make available for free and voluntarily has cost me quite a bit of time. Making the app available in Docker containers, with HTTPS... it took me a lot of time... I do it with pleasure... but also on my free time, my family time...
