### ISSUE TITLE
Feature request: minimal handling tasks notes - allowing to hide completed

### ISSUE THREAD

**Issue by taophp** [joplin-vieweb/joplin-vieweb#64]
I've just installed Joplin Viewweb and it's impressive. I love it but...
I use Joplin, both desktop and mobile, a lot. One of my use case is tasks management. Well, it should not be a real problem if I can't handle it with Vieweb, but all this old tasks became again visible in Vieweb, there is many of them (for years now!), and I can't hide them...

So here is my request : add an option to hide completed task notes. I know it may have more implications from a developer point of view, but, well, missing this feature make Vieweb hard to use for me, so this is my request :)

**Comment by gri38** [comment]
Hello.

Please see [https://github.com/joplin-vieweb/joplin-vieweb/releases/tag/v2.7.1](https://github.com/joplin-vieweb/joplin-vieweb/releases/tag/v2.7.1)

Let me know if it's ok for your (completed tasks are not hidden, they are greyed, like in Joplin App if I'm right.
