### ISSUE TITLE
Can't save sync config

### ISSUE THREAD

**Issue by symphonyoffeelings** [joplin-vieweb/joplin-vieweb#68]
Hi, I just set up Joplin-Vieweb. It's running in Docker on its own server, and connects through a reverse proxy (Apache2) through my subdomain.

I am unable to save the configuration from the web UI for synchronization. I can input all the information, but when I click "save" nothing happens, and nothing gets logged either. Setting up users in the admin panel worked fine, FWIW.

When I go to sync, it just says "Not authenticated with (None). Please provide any missing credentials." I've tried both Chrome and Firefox.

What can I do to troubleshoot this?

**Comment by symphonyoffeelings** [comment]
Also, the "test" button is missing for me.

**Comment by qiudaomao** [comment]
same here, when click save, console report errors.
`An invalid form control with name='s3region' is not focusable.`
![image](https://github.com/joplin-vieweb/joplin-vieweb/assets/4716508/6cda67bb-89a1-46da-a8fc-5062c6f28858)

**Comment by gri38** [comment]
Thanks for feedback.
The recent addition of S3 as target broke the other ones.

I'll fix it.

**Comment by gri38** [comment]
Hello.

Thanks for your patience @qiudaomao  and @symphonyoffeelings .
A small bug fix at the end of the weekend: that should be fix on [the latest version (2.5.1)](https://github.com/joplin-vieweb/joplin-vieweb/releases/tag/v2.5.1).

Don't forget to refresh your webbrowser (Ctrl + F5 on the joplin page).

Let me know if that's ok for you (I tested on dev and on my running server).

BTW, @symphonyoffeelings : test button is displayed only for Nextcloud synchro target.

**Comment by symphonyoffeelings** [comment]
It works! Thank you so much!

**Comment by gri38** [comment]
> It works! Thank you so much!

Great! Thanks for feedback!
